// ─────────────────────────────────────────────────────────────────────────────
// Public discovery hubs — /food /shopping /travel /entertainment /spa
//
// The GEO / AI-search surface. Each hub is a static, crawlable page that says
// what Tappy does in that domain (the five canonical product categories in
// `CATEGORIES`), offers real example questions, and lists the newest PUBLIC
// shared results in the domain. Nothing here is generated by a model and no
// external data is crawled: the useful content is what the product already
// produced and users chose to make public.
//
// 🔑 THIS FILE OWNS NO TEXT. Every string comes from the canonical i18n
// dictionary (`src/lib/i18n/discovery.ts`, `hub.*`), read here into a typed
// shape so the page and its tests never touch raw keys.
// ─────────────────────────────────────────────────────────────────────────────

import { CATEGORIES, type CategoryId } from '@/lib/utils'
import { hubText, type HubLocale } from '@/lib/i18n/discovery'

export const HUB_DOMAINS: readonly CategoryId[] = CATEGORIES.map(c => c.id)

export function isHubDomain(v: unknown): v is CategoryId {
  return typeof v === 'string' && (HUB_DOMAINS as readonly string[]).includes(v)
}

export interface HubCopy {
  title: string
  description: string
  h1: string
  intro: string
  /** Real questions Tappy answers well in this domain — each is a link into chat. */
  examples: string[]
  faq: Array<{ q: string; a: string }>
}

export const HUB_EXAMPLE_COUNT = 4
export const HUB_FAQ_COUNT = 2

/** The hub's content for a locale, read from the dictionary. Pure. */
export function hubCopy(domain: CategoryId, locale: HubLocale, t: (key: string) => string = (k) => hubText(locale, k)): HubCopy {
  const k = (suffix: string) => t(`hub.${domain}.${suffix}`)
  return {
    title: k('title'),
    description: k('description'),
    h1: k('h1'),
    intro: k('intro'),
    examples: Array.from({ length: HUB_EXAMPLE_COUNT }, (_, i) => k(`example${i + 1}`)),
    faq: Array.from({ length: HUB_FAQ_COUNT }, (_, i) => ({ q: k(`faq${i + 1}.q`), a: k(`faq${i + 1}.a`) })),
  }
}
