import Foundation

struct ZodiacSign: Identifiable {
    let id: String
    let nameVi: String
    let nameEn: String
    let emoji: String
    let dateRangeLabel: String
    let startMonth: Int
    let startDay: Int
    let endMonth: Int
    let endDay: Int
    let element: String
    let ruling: String
    let traits: String
    let banks: FortuneBanks
}

enum ZodiacData {
    static func getByDate(month: Int, day: Int) -> ZodiacSign {
        for sign in signs {
            if sign.startMonth == sign.endMonth {
                if month == sign.startMonth && day >= sign.startDay && day <= sign.endDay { return sign }
            } else if sign.startMonth > sign.endMonth {
                if (month == sign.startMonth && day >= sign.startDay) ||
                   (month == sign.endMonth && day <= sign.endDay) { return sign }
            } else {
                if (month == sign.startMonth && day >= sign.startDay) ||
                   (month == sign.endMonth && day <= sign.endDay) { return sign }
            }
        }
        return signs[0]
    }

    static let signs: [ZodiacSign] = [
        ZodiacSign(id: "aries", nameVi: "Bạch Dương", nameEn: "Aries", emoji: "♈", dateRangeLabel: "21/3 – 19/4", startMonth: 3, startDay: 21, endMonth: 4, endDay: 19, element: "Lửa", ruling: "Sao Hoả", traits: "Năng động, dũng cảm, quyết đoán, thích dẫn đầu", banks: FortuneBanks(love: ["Tình cảm sôi nổi, nhiệt huyết trong các mối quan hệ.", "Cơ hội gặp gỡ người mới qua hoạt động xã hội.", "Cần kiên nhẫn hơn để hiểu đối phương sâu sắc.", "Tình yêu đến bất ngờ từ người quen lâu năm."], career: ["Thời điểm tốt để khởi xướng dự án mới.", "Lãnh đạo bẩm sinh giúp bạn nổi bật trong đội nhóm.", "Cần kiểm soát sự nóng vội để tránh sai lầm.", "Cơ hội thăng tiến đến từ sáng kiến cá nhân."], money: ["Thu nhập tăng nhờ sự chủ động và nỗ lực.", "Tránh chi tiêu bốc đồng theo cảm xúc.", "Đầu tư ngắn hạn có thể mang lại lợi nhuận.", "Tiết kiệm từ bây giờ cho kế hoạch lớn sắp tới."], health: ["Năng lượng dồi dào, phù hợp tập luyện cường độ cao.", "Chú ý vùng đầu và cơ bắp khi vận động.", "Cần nghỉ ngơi đủ để tránh kiệt sức.", "Yoga hoặc thiền giúp cân bằng năng lượng."], luckyNumbers: [1, 9, 17, 21], luckyColors: ["Đỏ", "Cam", "Vàng"])),
        ZodiacSign(id: "taurus", nameVi: "Kim Ngưu", nameEn: "Taurus", emoji: "♉", dateRangeLabel: "20/4 – 20/5", startMonth: 4, startDay: 20, endMonth: 5, endDay: 20, element: "Đất", ruling: "Sao Kim", traits: "Kiên định, thực tế, yêu cái đẹp, trung thành", banks: FortuneBanks(love: ["Tình cảm ổn định, mối quan hệ bền vững.", "Cần chủ động hơn để không bỏ lỡ cơ hội.", "Sự chung thuỷ được đền đáp xứng đáng.", "Thời điểm tốt để cam kết lâu dài."], career: ["Sự kiên trì mang lại thành quả rõ rệt.", "Cơ hội tài chính liên quan đến bất động sản.", "Đừng ngại thay đổi khi cơ hội tốt xuất hiện.", "Công việc sáng tạo phát triển thuận lợi."], money: ["Tài chính ổn định nhờ quản lý tốt.", "Có cơ hội tăng thu nhập thụ động.", "Đầu tư dài hạn là lựa chọn khôn ngoan.", "Tránh cho vay số tiền lớn trong thời gian này."], health: ["Sức khỏe tốt nếu duy trì lối sống điều độ.", "Chú ý vùng cổ họng và tuyến giáp.", "Ẩm thực lành mạnh là nền tảng sức khỏe.", "Đi bộ trong thiên nhiên giúp thư giãn."], luckyNumbers: [2, 6, 14, 24], luckyColors: ["Xanh lá", "Hồng", "Trắng"])),
        ZodiacSign(id: "gemini", nameVi: "Song Tử", nameEn: "Gemini", emoji: "♊", dateRangeLabel: "21/5 – 20/6", startMonth: 5, startDay: 21, endMonth: 6, endDay: 20, element: "Khí", ruling: "Sao Thuỷ", traits: "Linh hoạt, thông minh, giao tiếp tốt, đa tài", banks: FortuneBanks(love: ["Giao tiếp tốt giúp mối quan hệ thăng hoa.", "Nhiều lựa chọn tình cảm, cần tỉnh táo.", "Sự hài hước thu hút người khác đến gần.", "Cần chung thuỷ và kiên định hơn."], career: ["Kỹ năng giao tiếp mở ra nhiều cơ hội.", "Thích hợp làm việc nhóm và brainstorm.", "Cẩn thận với việc nhận quá nhiều dự án cùng lúc.", "Viết lách và truyền thông là thế mạnh."], money: ["Thu nhập đa dạng từ nhiều nguồn.", "Cần kiểm soát chi tiêu cho sở thích.", "Kinh doanh online có tiềm năng tốt.", "Tránh quyết định tài chính khi đang dao động."], health: ["Hệ thần kinh cần được chăm sóc.", "Tập thể dục giúp giải toả stress.", "Giấc ngủ đủ giấc rất quan trọng.", "Hoạt động ngoài trời tốt cho tinh thần."], luckyNumbers: [3, 5, 12, 23], luckyColors: ["Vàng", "Xanh dương nhạt", "Bạc"])),
        ZodiacSign(id: "cancer", nameVi: "Cự Giải", nameEn: "Cancer", emoji: "♋", dateRangeLabel: "21/6 – 22/7", startMonth: 6, startDay: 21, endMonth: 7, endDay: 22, element: "Nước", ruling: "Mặt Trăng", traits: "Nhạy cảm, chu đáo, bảo vệ gia đình, trực giác mạnh", banks: FortuneBanks(love: ["Tình cảm sâu đậm, gắn bó với gia đình.", "Trực giác giúp hiểu được cảm xúc đối phương.", "Cần mở lòng hơn với người mới.", "Kỷ niệm đẹp giúp củng cố mối quan hệ."], career: ["Công việc liên quan đến chăm sóc phát triển tốt.", "Môi trường làm việc ấm áp giúp tăng hiệu suất.", "Lãnh đạo bằng sự đồng cảm và lắng nghe.", "Dự án dài hạn cho kết quả tốt hơn ngắn hạn."], money: ["Quản lý tài chính gia đình tốt.", "Tiết kiệm cho những điều quan trọng.", "Bất động sản là kênh đầu tư phù hợp.", "Tránh cho mượn tiền vì tình cảm."], health: ["Chú ý hệ tiêu hoá và dạ dày.", "Cảm xúc ảnh hưởng lớn đến sức khỏe.", "Nấu ăn tại nhà tốt cho sức khỏe.", "Bơi lội là môn thể thao phù hợp."], luckyNumbers: [2, 7, 11, 22], luckyColors: ["Bạc", "Trắng", "Xanh biển"])),
        ZodiacSign(id: "leo", nameVi: "Sư Tử", nameEn: "Leo", emoji: "♌", dateRangeLabel: "23/7 – 22/8", startMonth: 7, startDay: 23, endMonth: 8, endDay: 22, element: "Lửa", ruling: "Mặt Trời", traits: "Tự tin, hào phóng, sáng tạo, thích sân khấu", banks: FortuneBanks(love: ["Sự tự tin thu hút người khác đến gần.", "Cần lắng nghe đối phương nhiều hơn.", "Tình yêu lãng mạn và đầy sáng tạo.", "Thể hiện tình cảm qua hành động cụ thể."], career: ["Khả năng lãnh đạo được công nhận.", "Sáng tạo mở ra cơ hội mới.", "Sân khấu và nghệ thuật là lĩnh vực nổi bật.", "Cần chia sẻ ánh sáng với đồng đội."], money: ["Thu nhập tăng nhờ tài năng cá nhân.", "Cẩn thận với chi tiêu xa xỉ.", "Đầu tư vào bản thân mang lại lợi nhuận cao.", "Quản lý tài chính cần kỷ luật hơn."], health: ["Tim mạch và lưng cần được chú ý.", "Hoạt động sáng tạo tốt cho tinh thần.", "Ánh nắng mặt trời mang lại năng lượng.", "Cần cân bằng giữa công việc và nghỉ ngơi."], luckyNumbers: [1, 4, 10, 19], luckyColors: ["Vàng", "Cam", "Đỏ"])),
        ZodiacSign(id: "virgo", nameVi: "Xử Nữ", nameEn: "Virgo", emoji: "♍", dateRangeLabel: "23/8 – 22/9", startMonth: 8, startDay: 23, endMonth: 9, endDay: 22, element: "Đất", ruling: "Sao Thuỷ", traits: "Tỉ mỉ, phân tích, thực tế, cầu toàn", banks: FortuneBanks(love: ["Sự tỉ mỉ giúp chăm sóc đối phương chu đáo.", "Cần bớt cầu toàn trong tình cảm.", "Tình yêu đến từ sự tin tưởng và chia sẻ.", "Quan hệ phát triển khi bạn buông bỏ kiểm soát."], career: ["Chi tiết và tổ chức là thế mạnh lớn.", "Phân tích dữ liệu và nghiên cứu thuận lợi.", "Cẩn thận với xu hướng tự phê bình quá mức.", "Công việc có hệ thống mang lại thành công."], money: ["Quản lý tài chính chi tiết và hiệu quả.", "Tiết kiệm được số tiền đáng kể.", "Phân tích kỹ trước khi đầu tư.", "Tránh bỏ lỡ cơ hội vì quá thận trọng."], health: ["Hệ tiêu hoá cần được quan tâm.", "Chế độ ăn cân bằng rất quan trọng.", "Stress có thể biểu hiện qua cơ thể.", "Thiên nhiên và vườn tược giúp thư giãn."], luckyNumbers: [5, 14, 23, 27], luckyColors: ["Xanh lá", "Nâu", "Be"])),
        ZodiacSign(id: "libra", nameVi: "Thiên Bình", nameEn: "Libra", emoji: "♎", dateRangeLabel: "23/9 – 22/10", startMonth: 9, startDay: 23, endMonth: 10, endDay: 22, element: "Khí", ruling: "Sao Kim", traits: "Công bằng, hài hòa, ngoại giao, yêu cái đẹp", banks: FortuneBanks(love: ["Sự hài hòa trong mối quan hệ được đề cao.", "Khả năng ngoại giao giúp giải quyết mâu thuẫn.", "Cần quyết đoán hơn trong tình cảm.", "Cặp đôi cùng phát triển và hỗ trợ nhau."], career: ["Hợp tác và đàm phán là thế mạnh.", "Công việc liên quan đến thẩm mỹ thuận lợi.", "Cần đưa ra quyết định nhanh hơn.", "Môi trường làm việc hài hòa tăng hiệu suất."], money: ["Cân bằng giữa chi tiêu và tiết kiệm.", "Hợp tác kinh doanh có tiềm năng tốt.", "Thẩm mỹ và nghệ thuật là nguồn thu nhập.", "Tránh do dự quá lâu với cơ hội tài chính."], health: ["Thận và lưng dưới cần được chú ý.", "Cân bằng cuộc sống là chìa khóa sức khỏe.", "Hoạt động nghệ thuật giúp thư giãn.", "Tránh bỏ bữa hoặc ăn uống không đều."], luckyNumbers: [6, 15, 24, 33], luckyColors: ["Hồng", "Xanh dương", "Tím nhạt"])),
        ZodiacSign(id: "scorpio", nameVi: "Bọ Cạp", nameEn: "Scorpio", emoji: "♏", dateRangeLabel: "23/10 – 21/11", startMonth: 10, startDay: 23, endMonth: 11, endDay: 21, element: "Nước", ruling: "Sao Diêm Vương", traits: "Sâu sắc, quyết tâm, bí ẩn, trực giác mạnh", banks: FortuneBanks(love: ["Tình cảm sâu đậm và đầy đam mê.", "Trực giác giúp nhận ra ý định thật của đối phương.", "Cần học cách tin tưởng và buông bỏ.", "Sự chung thuỷ tạo nền tảng mối quan hệ bền vững."], career: ["Nghiên cứu và phân tích sâu là thế mạnh.", "Khả năng biến đổi và tái tạo giúp vượt khó.", "Cẩn thận với sự đa nghi trong công việc.", "Lãnh đạo bằng tầm nhìn dài hạn."], money: ["Trực giác tốt trong đầu tư.", "Quản lý tài chính bí mật và hiệu quả.", "Cơ hội từ lĩnh vực chuyên sâu.", "Tránh đầu tư theo cảm xúc tiêu cực."], health: ["Hệ sinh sản và bài tiết cần quan tâm.", "Cảm xúc kìm nén ảnh hưởng sức khỏe.", "Bơi lội và yoga phù hợp với bạn.", "Thải độc cơ thể định kỳ có lợi."], luckyNumbers: [8, 11, 18, 22], luckyColors: ["Đỏ đậm", "Đen", "Tím"])),
        ZodiacSign(id: "sagittarius", nameVi: "Nhân Mã", nameEn: "Sagittarius", emoji: "♐", dateRangeLabel: "22/11 – 21/12", startMonth: 11, startDay: 22, endMonth: 12, endDay: 21, element: "Lửa", ruling: "Sao Mộc", traits: "Lạc quan, phiêu lưu, trung thực, yêu tự do", banks: FortuneBanks(love: ["Tình yêu gắn liền với tự do và khám phá.", "Sự lạc quan thu hút nhiều người xung quanh.", "Cần cam kết hơn trong mối quan hệ.", "Du lịch cùng nhau gắn kết tình cảm."], career: ["Cơ hội quốc tế và mở rộng tầm nhìn.", "Giáo dục và truyền cảm hứng là thế mạnh.", "Cần hoàn thành trước khi bắt đầu mới.", "Sự lạc quan giúp vượt qua khó khăn."], money: ["May mắn trong các cơ hội bất ngờ.", "Cẩn thận với rủi ro do quá tự tin.", "Kinh doanh liên quan đến du lịch thuận lợi.", "Đa dạng hoá thu nhập là hướng đi tốt."], health: ["Hông và đùi cần được chú ý.", "Hoạt động ngoài trời tốt cho sức khỏe.", "Cần kiểm soát cân nặng.", "Thể thao mạo hiểm cần an toàn."], luckyNumbers: [3, 9, 12, 21], luckyColors: ["Tím", "Xanh lam", "Cam"])),
        ZodiacSign(id: "capricorn", nameVi: "Ma Kết", nameEn: "Capricorn", emoji: "♑", dateRangeLabel: "22/12 – 19/1", startMonth: 12, startDay: 22, endMonth: 1, endDay: 19, element: "Đất", ruling: "Sao Thổ", traits: "Kỷ luật, tham vọng, kiên nhẫn, thực tế", banks: FortuneBanks(love: ["Tình cảm nghiêm túc và hướng đến lâu dài.", "Cần thể hiện cảm xúc nhiều hơn.", "Sự ổn định và an toàn thu hút đối phương.", "Xây dựng tình yêu như xây nhà — từ nền tảng."], career: ["Kỷ luật và kiên nhẫn mang lại thăng tiến.", "Mục tiêu dài hạn đang trong tầm tay.", "Lãnh đạo bằng kết quả thực tế.", "Đừng quá tham công tiếc việc."], money: ["Tài chính ổn định nhờ kế hoạch cẩn thận.", "Đầu tư dài hạn mang lại lợi nhuận bền.", "Sự tiết kiệm tích luỹ thành tài sản lớn.", "Bất động sản và chứng khoán dài hạn phù hợp."], health: ["Xương khớp và đầu gối cần chú ý.", "Công việc quá tải ảnh hưởng sức khỏe.", "Leo núi và đi bộ phù hợp với bạn.", "Cần thời gian thư giãn và giải trí."], luckyNumbers: [4, 8, 13, 22], luckyColors: ["Nâu", "Đen", "Xám"])),
        ZodiacSign(id: "aquarius", nameVi: "Bảo Bình", nameEn: "Aquarius", emoji: "♒", dateRangeLabel: "20/1 – 18/2", startMonth: 1, startDay: 20, endMonth: 2, endDay: 18, element: "Khí", ruling: "Sao Thiên Vương", traits: "Sáng tạo, độc lập, nhân đạo, phi truyền thống", banks: FortuneBanks(love: ["Tình yêu dựa trên sự kết nối trí tuệ.", "Cần mở lòng hơn về mặt cảm xúc.", "Bạn bè có thể trở thành tình yêu.", "Sự độc đáo của bạn thu hút đối phương."], career: ["Đổi mới và công nghệ là thế mạnh.", "Dự án cộng đồng mang lại ý nghĩa.", "Suy nghĩ đột phá được đánh giá cao.", "Cần hợp tác thay vì làm một mình."], money: ["Đầu tư công nghệ có tiềm năng.", "Thu nhập từ sáng tạo và đổi mới.", "Tránh quá lý tưởng với kế hoạch tài chính.", "Kinh tế chia sẻ và gây quỹ phù hợp."], health: ["Mắt cá chân và hệ tuần hoàn cần quan tâm.", "Hoạt động nhóm tốt cho tinh thần.", "Công nghệ hỗ trợ theo dõi sức khỏe.", "Cần tránh xa stress từ mạng xã hội."], luckyNumbers: [4, 7, 11, 29], luckyColors: ["Xanh dương", "Bạc", "Tím"])),
        ZodiacSign(id: "pisces", nameVi: "Song Ngư", nameEn: "Pisces", emoji: "♓", dateRangeLabel: "19/2 – 20/3", startMonth: 2, startDay: 19, endMonth: 3, endDay: 20, element: "Nước", ruling: "Sao Hải Vương", traits: "Nhạy cảm, nghệ thuật, đồng cảm, giàu trí tưởng tượng", banks: FortuneBanks(love: ["Tình cảm lãng mạn và đầy mơ mộng.", "Sự đồng cảm giúp hiểu đối phương sâu sắc.", "Cần phân biệt rõ giữa mơ và thực.", "Nghệ thuật gắn kết hai tâm hồn."], career: ["Sáng tạo và nghệ thuật phát triển mạnh.", "Trực giác giúp đưa ra quyết định đúng.", "Công việc có ý nghĩa xã hội phù hợp.", "Cần tổ chức tốt hơn để tránh phân tán."], money: ["Trực giác tốt nhưng cần kiểm tra thực tế.", "Nghệ thuật có thể trở thành nguồn thu.", "Cẩn thận với sự mơ mộng trong tài chính.", "Thiện nguyện mang lại may mắn bất ngờ."], health: ["Bàn chân và hệ miễn dịch cần chú ý.", "Nước là yếu tố chữa lành cho bạn.", "Âm nhạc và nghệ thuật giảm stress.", "Ranh giới cảm xúc giúp bảo vệ năng lượng."], luckyNumbers: [3, 7, 12, 16], luckyColors: ["Xanh biển", "Tím", "Bạc"])),
    ]
}
