/**
 * P1 PILOT — `ts.privacy.personal-information`.
 *
 * ============================================================================
 * WHAT THIS FILE IS
 * ============================================================================
 * The constitutive predicate for one policy, plus the signal layer that feeds
 * it. It is the first per-policy detection content in the repository.
 *
 * 🚨 THIS IS PRODUCT CONTENT, NOT CORPUS CONTENT. The corpus contains no
 * predicates — the word `predicate` appears zero times in
 * `02_POLICY_TAXONOMY.md`, and the generated registry says in its own header
 * that it holds none. Nothing in this file is derived from, generated by, or
 * authoritative over the corpus, and nothing here may be read back into it.
 *
 * 🚨 PLACEMENT DOES NOT RESOLVE `G02-D-11`. That decision — whether policy is
 * data or prose only, and who owns policy-platform engineering — remains OPEN.
 * This file lives beside the engine because that is where the existing
 * architecture puts pure, I/O-free policy code; the location is technical and
 * reversible, and it settles no authority question. Ownership of predicate
 * CONTENT is likewise unassigned (Group 01 §5.1 lists nine roles as "OWNER
 * ASSIGNMENT REQUIRED").
 *
 * ============================================================================
 * THE FROZEN PRODUCT CONTRACT (Owner, 2026-08-17) — DO NOT REINTERPRET
 * ============================================================================
 *   1. Sufficient evidence            → the approved classification behaviour.
 *   2. Missing consent / non-consent  → UNDETERMINED.
 *   3. A violation is NEVER inferred merely because consent evidence is absent.
 *   4. No rule may be added solely to move the measured 6/8 to 8/8.
 *   5. 6/8 is the correct target, not a temporary threshold.
 *   6. `UAT-PPI-1` and `EXP-PRIV-2` becoming a violation is a REGRESSION.
 *   7. No new outcome class · no enforcement · no user-report flow.
 *
 * Clause 3 is enforced structurally rather than by convention:
 * {@link exposureConstitutedFrom} has exactly ONE path that returns `true`, and
 * it is unreachable unless a caller supplies `ESTABLISHED_ABSENT` consent
 * evidence. No accumulation of other signals can reach it.
 *
 * ============================================================================
 * WHY ONE FIELD AND NOT SIX
 * ============================================================================
 * Measured, not assumed: the engine tests faults BEFORE truth, so one absent
 * field anywhere in a conjunction yields `INSUFFICIENT_EVIDENCE` even when a
 * different branch has definitely established `FALSE`. A six-branch predicate —
 * one branch per `Does not govern` item — therefore scored 2/8 against the
 * existing UAT bed, returning "cannot tell" even for a restaurant's own phone
 * number, which the corpus plainly places outside the policy. Consolidating the
 * carve-outs into one constitutive field scored 6/8 with the same signals.
 *
 * The carve-outs are handled here, in the signal layer, and NOT as a
 * `defeatingContext`. A defeating context yields `APPLICABLE_NO_VIOLATION`,
 * whereas every false-positive scenario in the bed requires `NOT_APPLICABLE`.
 * WF-6 agrees: all eighteen records declare `defeating_contexts: none`, so a
 * carve-out is constitutive, not an excuse.
 *
 * ============================================================================
 * OBSERVATION ONLY
 * ============================================================================
 * Pure functions. No I/O, no storage, no scheduling, no network, no clock —
 * `asOf` is always supplied by the caller. Nothing here can change visibility,
 * ranking, ordering, recommendation or notification, and there is no vocabulary
 * in which to express such a thing. This module is not imported by any route.
 */

import { evaluatePolicy, type PolicyDecision } from '../engine/evaluator';
import type { Expression } from '../engine/expression';
import type { PolicyProbe } from '../explore/observation';
import { defaultPolicyProvider } from '../provider';
import type { PolicyRecord } from '../types';

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/** The one policy this pilot covers. P2 is not implemented. */
export const P1_POLICY = 'ts.privacy.personal-information' as const;

/**
 * The versioned reference this pilot cites.
 *
 * VER-T1: "Decisions cite the version", and the provider deliberately refuses
 * to resolve a bare identity to "the latest" — guessing one would make a
 * decision record unexplainable after the fact. So the version is written here,
 * on purpose, and `privacyPolicyRecord()` fails loudly if the registry no
 * longer carries it. A corpus version bump must be a visible edit to this line,
 * never a silent re-point.
 */
export const P1_POLICY_REF = `${P1_POLICY}@1` as const;

/**
 * §9.4 `Does not govern`, verbatim, as the list this signal layer must honour:
 * already-public information in its ordinary context · self-disclosure ·
 * journalism in the public interest · business contact details · information
 * shared with consent.
 *
 * Exported so a test can assert the signal layer covers every item rather than
 * silently dropping one.
 */
export const P1_CARVE_OUTS = [
  'alreadyPublicInOrdinaryContext',
  'selfDisclosure',
  'journalismInPublicInterest',
  'subjectIsBusinessContact',
  'consentGiven',
] as const;

// ---------------------------------------------------------------------------
// The predicate — pure data, one field
// ---------------------------------------------------------------------------

/** The subject path the predicate reads. Exported so tests cannot drift from it. */
export const P1_SUBJECT_PATH = 'exposure.constituted' as const;

/**
 * The constitutive predicate.
 *
 * One comparison over one field. Every carve-out and every element of `Governs`
 * is resolved by {@link exposureConstitutedFrom} before this is evaluated, for
 * the fault-before-truth reason documented above.
 */
export const P1_PREDICATE: Expression = Object.freeze({
  op: 'eq',
  left: { ref: P1_SUBJECT_PATH },
  right: { value: true },
}) as Expression;

// ---------------------------------------------------------------------------
// Signals
// ---------------------------------------------------------------------------

/**
 * What is known about consent.
 *
 * Three states, because two would force "no evidence" to masquerade as one of
 * the answers — the exact collapse clause 3 of the freeze forbids.
 *
 * `ESTABLISHED_ABSENT` requires positive evidence that the subject did not
 * consent. **No such evidence source exists in TappyAI today**: there is no
 * report flow for reviews or posts, and the freeze forbids adding one here. So
 * in production this value is currently unreachable, and the positive path is
 * consequently unreachable — which is precisely the accepted 6/8 behaviour.
 */
export const CONSENT_EVIDENCE = ['ESTABLISHED_GIVEN', 'ESTABLISHED_ABSENT', 'NO_EVIDENCE'] as const;
export type ConsentEvidence = (typeof CONSENT_EVIDENCE)[number];

/**
 * Everything the predicate depends on.
 *
 * 🔑 `undefined` means "could not be established" and is NEVER interchangeable
 * with `false`. `false` is a finding — that the carve-out does not apply, or
 * that no identifying information is present. A detector that writes `false`
 * for something it merely did not check manufactures findings silently.
 */
export interface PrivacySignals {
  /**
   * Identifying information about a person is present in the content.
   *
   * ⚠ The extractor in this file returns `true` or `undefined`, never `false`:
   * finding no contact pattern is not the same as establishing that no
   * identifying information is present (a home address written in prose matches
   * nothing). A caller with stronger evidence may supply `false` directly.
   */
  readonly identifyingInformationPresent?: boolean;
  /** The information concerns someone other than the posting account. */
  readonly subjectIsAnotherPerson?: boolean;
  /** §9.4: business contact details. */
  readonly subjectIsBusinessContact?: boolean;
  /** §9.4: self-disclosure. */
  readonly selfDisclosure?: boolean;
  /** §9.4: already-public information in its ordinary context. */
  readonly alreadyPublicInOrdinaryContext?: boolean;
  /** §9.4: journalism in the public interest. */
  readonly journalismInPublicInterest?: boolean;
  /** §9.4: information shared with consent — and its two counterparts. */
  readonly consentEvidence?: ConsentEvidence;
}

// ---------------------------------------------------------------------------
// The constitutive question
// ---------------------------------------------------------------------------

/**
 * Is the policy constituted for this content?
 *
 * `true` / `false` / `undefined`, where `undefined` means the record does not
 * support an answer and the engine should report uncertainty.
 *
 * 🔒 FREEZE CLAUSE 3, STRUCTURALLY: there is exactly one `return true` below and
 * it is guarded by `ESTABLISHED_ABSENT`. Absent consent evidence falls to
 * `undefined`. `privacy pilot: the only path to true` in the test suite asserts
 * this exhaustively across the whole signal space, so a future edit that adds a
 * second positive path fails immediately.
 */
export function exposureConstitutedFrom(signals: PrivacySignals): boolean | undefined {
  // 1. An established carve-out settles it: nothing is constituted, so there is
  //    no exception to grant (§2.1). These are checked first because each one
  //    is decisive on its own.
  if (signals.subjectIsBusinessContact === true) return false;
  if (signals.selfDisclosure === true) return false;
  if (signals.subjectIsAnotherPerson === false) return false;
  if (signals.alreadyPublicInOrdinaryContext === true) return false;
  if (signals.journalismInPublicInterest === true) return false;
  if (signals.consentEvidence === 'ESTABLISHED_GIVEN') return false;

  // 2. Established absence of identifying information settles it too.
  if (signals.identifyingInformationPresent === false) return false;

  // 3. Not even the presence of identifying information could be established.
  if (signals.identifyingInformationPresent !== true) return undefined;

  // 4. Governed exposure is established. Consent is now decisive — §9.4 makes
  //    `Actor & target` decisive on consent and on self-disclosure versus
  //    disclosure of another.
  if (signals.consentEvidence === 'ESTABLISHED_ABSENT') return true;

  // 5. No consent evidence either way. FREEZE CLAUSE 2 and 3: uncertainty, and
  //    never a finding. This is the branch that makes the accepted result 6/8.
  return undefined;
}

/**
 * The evaluation subject.
 *
 * When the constitutive question cannot be answered the field is OMITTED, not
 * set to `null` or `false`. The engine reads an absent field as a fault and
 * reports `INSUFFICIENT_EVIDENCE`; a `false` would instead report
 * `NOT_APPLICABLE`, an affirmative finding of no violation.
 */
export function privacySubject(signals: PrivacySignals): Record<string, unknown> {
  const constituted = exposureConstitutedFrom(signals);
  return constituted === undefined ? { exposure: {} } : { exposure: { constituted } };
}

// ---------------------------------------------------------------------------
// Signal extraction — the part that reads content
// ---------------------------------------------------------------------------

/**
 * Content and the surrounding facts the platform already holds.
 *
 * 🔒 Only classified fields belong here. A like count would make the content
 * version churn on every interaction, and an author id would put identity into
 * a value that travels with the classification.
 */
export interface PrivacyDetectionInput {
  /** Body, caption and hashtags, already joined by the caller. */
  readonly text: string;
  /**
   * Contact strings the platform knows belong to the business this content is
   * about — place name, place address, and any known place contact values.
   *
   * ⚠ The Explore feed does NOT currently select place contact numbers, so in
   * production this list is usually just the name and address and the business
   * carve-out will often stay unestablished. That yields uncertainty, never a
   * finding, so the gap is safe — but it is a gap, not a solved problem.
   */
  readonly businessContactStrings?: readonly (string | null | undefined)[];
  /** Contact strings the platform knows belong to the posting account. */
  readonly authorContactStrings?: readonly (string | null | undefined)[];
  /** Supplied by an evidence source. Defaults to `NO_EVIDENCE`. */
  readonly consentEvidence?: ConsentEvidence;
  /** Supplied only where something outside this file established it. */
  readonly alreadyPublicInOrdinaryContext?: boolean;
  /** Supplied only where something outside this file established it. */
  readonly journalismInPublicInterest?: boolean;
}

/**
 * Vietnamese phone shapes, deliberately conservative.
 *
 * The digit-boundary guards are load-bearing: without the leading `(?<!\d)` a
 * price like `100.000.000đ` matches as a phone number. That could only ever
 * produce uncertainty here, never a finding — but a detector that cries wolf
 * inflates the pilot's "cannot tell" rate, which is the pilot's headline metric.
 */
const PHONE_PATTERN = /(?<!\d)(?:\+84|0)(?:[\s.\-]?\d){8,10}(?!\d)/g;
const EMAIL_PATTERN = /[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/g;

/** Comparison form: digits and letters only, lower-cased. */
function normalise(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/** Every contact-shaped string in the text, in normalised comparison form. */
export function contactIdentifiersIn(text: string): string[] {
  const found = [...text.matchAll(PHONE_PATTERN), ...text.matchAll(EMAIL_PATTERN)].map((m) =>
    normalise(m[0]),
  );
  return [...new Set(found)].filter((v) => v.length > 0);
}

/**
 * Turns content into signals.
 *
 * Establishes only what the available data supports, and leaves everything else
 * `undefined`. In particular it never returns `identifyingInformationPresent:
 * false` and never returns `subjectIsBusinessContact: false` — neither absence
 * is observable from the fields the platform holds.
 */
export function detectPrivacySignals(input: PrivacyDetectionInput): PrivacySignals {
  const identifiers = contactIdentifiersIn(input.text);
  const present = identifiers.length > 0 ? true : undefined;

  const haystack = (values: readonly (string | null | undefined)[] | undefined): string =>
    (values ?? []).filter((v): v is string => typeof v === 'string').map(normalise).join(' ');

  const business = haystack(input.businessContactStrings);
  const author = haystack(input.authorContactStrings);

  const matchesBusiness = identifiers.some((id) => business.includes(id));
  const matchesAuthor = identifiers.some((id) => author.includes(id));

  return {
    ...(present === undefined ? {} : { identifyingInformationPresent: present }),
    ...(matchesBusiness ? { subjectIsBusinessContact: true } : {}),
    ...(matchesAuthor ? { selfDisclosure: true } : {}),
    ...(input.alreadyPublicInOrdinaryContext === undefined
      ? {}
      : { alreadyPublicInOrdinaryContext: input.alreadyPublicInOrdinaryContext }),
    ...(input.journalismInPublicInterest === undefined
      ? {}
      : { journalismInPublicInterest: input.journalismInPublicInterest }),
    consentEvidence: input.consentEvidence ?? 'NO_EVIDENCE',
  };
}

// ---------------------------------------------------------------------------
// Composition with the existing engine and observation seam
// ---------------------------------------------------------------------------

/** The registry record, through the sanctioned provider seam. */
export function privacyPolicyRecord(): PolicyRecord {
  const found = defaultPolicyProvider.getById(P1_POLICY_REF);
  if (found.state !== 'FOUND') {
    throw new Error(`P1 pilot: ${P1_POLICY_REF} not available from the provider (${found.state})`);
  }
  return found.record;
}

/**
 * The probe for the Explore observation seam.
 *
 * Carries the policy and the predicate only. The subject travels with the
 * caller's `evaluate` callback, exactly as the seam intends.
 */
export function privacyProbe(): PolicyProbe {
  return { policy: P1_POLICY_REF, predicate: P1_PREDICATE };
}

/**
 * One decision for one piece of content.
 *
 * Returns a `PolicyDecision` and nothing else — no action, no severity, no
 * visibility, no ordering. `asOf` is the caller's; this module reads no clock.
 */
export function evaluatePrivacy(signals: PrivacySignals, asOf: string): PolicyDecision {
  return evaluatePolicy(privacyPolicyRecord(), {
    subject: privacySubject(signals),
    predicate: P1_PREDICATE,
    asOf,
  });
}

/** Convenience: content in, decision out. Same guarantees as above. */
export function evaluatePrivacyContent(input: PrivacyDetectionInput, asOf: string): PolicyDecision {
  return evaluatePrivacy(detectPrivacySignals(input), asOf);
}
